[project]
name = "dummydicom"
version = "0.1.0"
description = "Test phi censoring"
readme = "readme.md"
requires-python = ">=3.12"
dependencies = [
    "pydicom",
    "deid",
    "deid-data>=0.0.20",
]
